experiment/test/e2e-testing/78

diff --git a/.github/workflows/k3d-dev-local.e2e.test.wfc.yml b/.github/workflows/k3d-dev-local.e2e.test.wfc.yml
--- a/.github/workflows/k3d-dev-local.e2e.test.wfc.yml
+++ b/.github/workflows/k3d-dev-local.e2e.test.wfc.yml
@@ -272,6 +272,13 @@ jobs:
           path: |
             infra/.cache
           key: k3d-dev-local
+      
+      - name: Cache hit check
+        run: |
+          if [ "${{ steps.terragrunt-cache-restore.outputs.cache-hit }}" != "true" ]; then
+            echo "Error: No cache hit, exiting."
+            exit 1
+          fi
 
       - name: Start devcontainer
         working-directory: infra
